export const IPC = {
  OPEN_EXTERNAL: "app:open-external",
  EXPORT_APP_DATA: "app:export-data",
  IMPORT_APP_DATA: "app:import-data",
  GET_PROFILES: "profiles:get",
  SAVE_PROFILES: "profiles:save",
  START_PROFILE: "profiles:start",
  STOP_PROFILE: "profiles:stop",
  GET_PROFILE_STATUSES: "profiles:get-statuses",
  LIST_SESSIONS: "app:list-sessions",
  GET_SESSION_TRACE: "trace:get-session",
  GET_EXCHANGE_DETAIL: "trace:get-exchange",
  GET_SESSION_DASHBOARD: "trace:get-session-dashboard",
  CLEAR_HISTORY: "trace:clear-history",
  GET_UPDATE_STATE: "app:get-update-state",
  CHECK_FOR_UPDATES: "app:check-for-updates",
  DOWNLOAD_UPDATE: "app:download-update",
  QUIT_AND_INSTALL_UPDATE: "app:quit-and-install-update",
  // main → renderer push events
  PROXY_ERROR: "proxy:error",
  TRACE_CAPTURED: "trace:captured",
  TRACE_RESET: "trace:reset",
  PROFILE_STATUS_CHANGED: "profiles:status-changed",
  PROFILES_CHANGED: "profiles:changed",
  UPDATE_STATE_CHANGED: "app:update-state-changed",
} as const;
